spring:
  application:
    name:
      Book_library


  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: alisher123
    driver-class-name: org.postgresql.Driver
