spring:
  application:
    name:
      Book_library



  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: alisher123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
